using System.Collections.Generic;
using System.IO;
using System.Linq;
using Dung.Ninja;
using Dung.Ninja.Objects;

namespace Dung.Lib
{
    public abstract class Project : IDependency
    {
        public Project(string buildDir)
        {
            BuildDir = buildDir;
            if (!Directory.Exists(BuildDir)) Directory.CreateDirectory(BuildDir);
        }

        public abstract IDependency Entrypoint { get; }

        public string BuildDir { get; }

        public abstract string Name { get; }

        public IEnumerable<IDependency>? Dependencies => new[]
        {
            Entrypoint
        };

        public IEnumerable<IDependency> FlattenDependencies()
        {
            return Dependencies.Concat(Dependencies.SelectMany(d => d.FlattenDependencies()));
        }

        public void WriteNinja()
        {
            var ninjaFile = Path.Join(BuildDir, "build.ninja");
            using var stream = File.Create(ninjaFile);
            using var streamWriter = new StreamWriter(stream) {AutoFlush = true};
            WriteNinja(streamWriter);
        }

        public void WriteNinja(StreamWriter writer)
        {
            List<IBuildable> buildables = FlattenDependencies().OfType<IBuildable>().ToList();

            var ninja = new NinjaSyntax(writer);
            ninja.Comment(
                "This file was generated by the dung build system. Please do not edit, as changes will be automatically overriden.");

            ninja.Newline();
            ninja.Comment("Build rules");
            foreach (Rule rule in buildables.Select(b => b.Rule).ToHashSet(new Rule.Comparer())) ninja.Rule(rule);

            ninja.Newline();
            ninja.Comment("Build artifacts");
            foreach (Build build in buildables.Select(b => b.GetBuild()).ToHashSet(new Build.Comparer()))
                ninja.Build(build);


            if (!(Entrypoint is IBuildable buildable)) return;
            ninja.Newline();
            ninja.Comment("Default artifact to build when invoked directly (without parameters)");
            ninja.Default(buildable.GetBuild());
        }
    }
}